version: '2'
services:
  mvn:
    image: base2/maven
    volumes:
      - $HOME/.m2/repository:/var/maven/.m2/repository
      - .:/app
  posters:
    image: "postgres:9.5"
    environment:
      POSTGRES_USER: jentrata
      POSTGRES_PASSWORD: jentrata
      POSTGRES_DB: jentrata
      DB_USER_NAME: corvus
      DB_USER_PASS: corvus
    volumes:
    - ./Dist/src/main/scripts/sql/as2.sql:/work/sql/as2.sql
    - ./Dist/src/main/scripts/sql/ebms.sql:/work/sql/ebms.sql
    - ./ContainerFiles/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
  jentrata-msh:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      - posters
      - activemq
      - mvn
    links:
      - posters:db
      - activemq:activemq
    environment:
      JENTRATA_DEBUG: "true"
      TOMCAT_USER_NAME: corvus
      TOMCAT_USER_PASS: corvus
      DB_USER_NAME: corvus
      DB_USER_PASS: corvus
      DB_HOST_NAME: db
      ACTIVEMQ_MODE: external
      ACTIVEMQ_URL: tcp://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASS: admin
  activemq:
    image: "webcenter/activemq"
    ports:
      - "8161:8161"